### ISSUE TITLE
Contact form with multiple lists fails to add new subscriber if previous lists already have the subscriber

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#14]
Setup:
- Create contact form with TWO contact lists
- In the first list, add a subscriber

Steps to reproduce:
1. Go to http://dev-benchmark-email-lite.pantheonsite.io
2. For Sample Signup Form, for Email, enter the same subscriber address as was entered in the Setup process above
3. Click Subscribe

Result:
System stated, "Successfully updated subscription." See Screenshot 1. No "Please confirm your subscription" email came. Subscriber was not added to the second list.

Expected result:
Since only the first list had the subscriber, expected the system to let the user know a confirmation email was on its way. And, ultimately, after the user clicked the confirmation link, to add the subscriber to the second list.

Workaround?
None

Reproducible?
Always

Occurs:
- Win Firefox 47.0 + BMEL 2.6 [68bcb3a]
- Win Chrome 51.0.2704.84 m (64-bit) + BMEL 2.6 [68bcb3a]

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16063209/d03fb434-324c-11e6-8e27-cb8abb86a1d3.png)

**Comment by seanconklin** [comment]
The problem here is that there is an API method to add a user to a sign up Form, but no method to update them on a Form. So, we check the Lists of the sign up Form and determine if the subscriber is already on one. If so, we run the update `listUpdateContactDetails` for all Lists in the Form. If not, we run the `listAddContactsForm` method.

The problem being described would occur (A) if a user had pre existed on a List then tried to sign up with a Form, plus (B) if the Form had a List added to it after the subscriber had signed up originally and they re-subscribe.

This is a good Benchmark Email topic, as we should ask them how we should be handling this situation, and maybe get a new API call to use for it.

**Comment by randywsandberg** [comment]
Wrote up a similar bug for version 3.x. See https://github.com/Coded-Commerce-LLC/WP-Benchmark-Email/issues/9 for more information. Once that bug has been fixed I will retry this test case on version 3.x. Closing this bug.
