### ISSUE TITLE
Subscription process fails when more than 100 characters are used in a field

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#20]
Steps to reproduce:
1. Go to http://35.160.89.203
2. For First Name, enter Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc aliquam lectus eu velit tempus nullam.X
3. For Last Name, enter Johnson
4. For Email, enter an active email address
5. Click Subscribe

Result:
System stated, "There was a problem saving your subscription. Please try again later." See screenshot.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/19838668/75851bfe-9e91-11e6-839b-18b3d8dac17f.png)

Expected Result:
System to state, "A verification email has been sent."

Workaround?
None

Reproducible?
Always

Occurs:
- Mac Chrome 54.0.2840.71 (64-bit) + > 100 characters
- Win Firefox 49.0.2 + > 100 characters

Doesn't Occur:
- Mac Chrome 54.0.2840.71 (64-bit) + <= 100 characters
- Win Firefox 49.0.2 + <= 100 characters

Notes:
Same results found over at http://dev-benchmark-email-lite.pantheonsite.io when testing our latest BMEL for WordPress.

**Comment by randywsandberg** [comment]
Note that all fields MAX out at 200 characters. Which is what Benchmark Email fields MAX out at.

**Comment by seanconklin** [comment]
Note that I just changed the Joomla! 3.x test URL to **http://ec2-54-67-15-144.us-west-1.compute.amazonaws.com/joomla3/** due to server upgrades and consolidations.

I'll contact Daniel and Jason about this one, since I can see the API is returning a NULL response any time we pass more than 100 characters over the XML-RPC API. From our recollection this used to accept up to the full 200 limit that the BenchmarkEmail UI has.

If they can't fix it soon, we may need to limit all fields to 100 characters until further notice. I'll update this once I have a response from them.
