### ISSUE TITLE
Using BLOCK editor, field outlines vanish after sending a test email or campaign

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#26]
**Steps to reproduce:**
1. Log in to https://dev-benchmark-email.pantheonsite.io/wp-admin/ as admin
2. Open a post using a BLOCK editor
3. Within Benchmark Email Lite box, enter a Subject
4. Make sure Send a test email is selected
5. Click Send
--> bug

**Expected result:**
Expected field outlines for "Email name", "From name", "Subject", "Send a test email" to remain visible.

**Observed result:**
Instead, field outlines disappear. **Issue also reproducible sending out either an immediate or scheduled delivery.**  See attached Before and After screenshots.

**Reproducible?**
Always

**Occurs:**
Latest dev BMEL + MS Edge 42.17134.1.0 using a BLOCK editor
Latest dev BMEL + Win Chrome 71.0.3578.98 using a BLOCK editor

**Doesn't occur:**
Latest dev BMEL + MS Edge 42.17134.1.0 using a Classic editor

**Before:**
![before](https://user-images.githubusercontent.com/19829655/50574829-17b4ca80-0da5-11e9-86ec-45dfc67760c1.PNG)

**After:**
![after](https://user-images.githubusercontent.com/19829655/50574832-226f5f80-0da5-11e9-85e7-0bb64ee933be.PNG)

**Comment by seanconklin** [comment]
This looks like intended behavior from WordPress that Metabox form fields do a form of hiding when the page is submitted, not something that comes from our plugin. Problem with that concerning Gutenberg is individual pieces submit instead of the whole page, so the fields don't re-appear between the user submitting the test email versus the actual campaign.

This overall seems minor because the user can still use it, and I'm afraid trying to fix it will conflict with a core JS/jQuery "feature".

**Comment by randywsandberg** [comment]
**Setup:**
- XAMPP for Linux 7.4.8
- WordPress 5.4.2
- Benchmark Email Lite 3.2
- Linux Chrome 84.0.4147.89

Issue no longer reproducible due to UI change. Closing as not to be fixed.
