### ISSUE TITLE
Our Emails page vs Benchmark Email's My Emails page

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#9]
Our current Emails page has two columns; Email Name and Date Modified. Plus, we denote the API key in the Email Name column's header. Very cool! We also include a Refresh Data link for obvious reasons. See Screenshot 1.

At benchmarkemail.com, they have five columns; Email Name, Status, Date Modified, Date Scheduled, and Tools (see Screenshot 2). The first four being sortable. For Tools they present three icons that include the following functionality; Report, Copy this Email, and, Delete this email. Plus, clicking the magnifying glass allows the user to Preview this Email whereas clicking on the Email title takes the user the same place our does -- to its top level Report page.

Anyway, this is just another enhancement request to see if it would make sense to bring any of their added functionality into our project. That is, Status, Date Scheduled, and Copy this Email sound pretty cool to me! ;-)

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15953161/912a956c-2e7c-11e6-8425-e15f5aacad50.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15953162/912abf56-2e7c-11e6-85b5-16088434f72b.png)

**Comment by seanconklin** [comment]
I checked and the API does provide the `Status` and `Date Scheduled` information and also offers a method `emailDelete`, so we can add all of those things.

The copying of an email is probably something not appropriate for WP since those emails are generated from posts and maintained as such, but we can discuss if you have any ideas.

The previewing of an email is not something that the API supports, but there could be a URL for viewing the web page version if that is enabled and available. I haven't seen that capability, but it could exist or be a Benchmark Email add on.

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to functionality change. Closing as not to be fixed.
